[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cities"
  pageRef = "/cities/"
  weight = 2

[[main]]
  name = "Attractions"
  pageRef = "/attractions/"
  weight = 3

[[main]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 4

[[main]]
  name = "Settling In"
  pageRef = "/settling-in/"
  parent = "Guides"
  weight = 1

[[main]]
  name = "Schools & Education"
  pageRef = "/schools-education/"
  parent = "Guides"
  weight = 2

[[main]]
  name = "Healthcare"
  pageRef = "/healthcare/"
  parent = "Guides"
  weight = 3

[[main]]
  name = "Transportation"
  pageRef = "/transportation/"
  parent = "Guides"
  weight = 4

[[main]]
  name = "Budgeting"
  pageRef = "/budgeting-cost-of-living/"
  parent = "Guides"
  weight = 5

[[main]]
  name = "Veterans & Military"
  pageRef = "/veterans-military/"
  parent = "Guides"
  weight = 6

[[main]]
  name = "Housing"
  pageRef = "/housing-guide/"
  parent = "Guides"
  weight = 7
